version: '3.8'

services:

  provider:
    container_name: provider
    build:
      context: ../launcher
    environment:
      IDS_WEBHOOK_ADDRESS: http://provider:8282
      EDC_CONNECTOR_NAME: ${PROVIDER_CONNECTOR_NAME}
      EDC_IDENTITY_DID_URL: ${PROVIDER_DID_URL}
      EDC_VAULT_NAME: ${PROVIDER_KEY_VAULT}
      EDC_VAULT_TENANTID: ${EDC_VAULT_TENANTID}
      EDC_VAULT_CLIENTID: ${EDC_VAULT_CLIENTID}
      EDC_VAULT_CLIENTSECRET: ${EDC_VAULT_CLIENTSECRET}
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      NODES_JSON_FILES_PREFIX: registry-
      NODES_JSON_DIR: /resources
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 1
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 1
    ports:
      - "9191:9191"
      - "8181:8181"
    volumes:
      - ./resources:/resources

  consumer:
    container_name: consumer
    build:
      context: ../launcher
    environment:
      IDS_WEBHOOK_ADDRESS: http://consumer:8282
      EDC_CONNECTOR_NAME: ${CONSUMER_CONNECTOR_NAME}
      EDC_IDENTITY_DID_URL: ${CONSUMER_DID_URL}
      EDC_VAULT_NAME: ${CONSUMER_KEY_VAULT}
      EDC_VAULT_TENANTID: ${EDC_VAULT_TENANTID}
      EDC_VAULT_CLIENTID: ${EDC_VAULT_CLIENTID}
      EDC_VAULT_CLIENTSECRET: ${EDC_VAULT_CLIENTSECRET}
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      NODES_JSON_FILES_PREFIX: registry-
      NODES_JSON_DIR: /resources
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 1
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 1
    ports:
      - "9192:9191"
      - "8182:8181"
    volumes:
      - ./resources:/resources
